name: GrantNieddu
favicon: null
layout_spectrum: 0.944159003905952
typography_spectrum: 0.7218700251542032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#008751'
    - '#234f33'
    - '#000000'
    - '#002b2b'
    - '#b4d4c4'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
